### ISSUE TITLE
Add Irena to Entrepreneur Track

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#22]
Twitter: @DamskyIrena

> Irena Damsky is an Israeli security and intelligence researcher with a disturbing affection to cats and unicorns. When she is not busy watching cartoons she is the VP Research for ThreatSTOP running the security analysis team and making the internet safer for everyone. In the past she used to work for Check Point, reached a rank of Captain (now in reserve) in the Israeli Defense forces and even managed to earn both an Bsc and Msc in computer science.

![irena-bio](https://user-images.githubusercontent.com/1035793/34228241-1558115a-e59e-11e7-8c1e-98bbf991d9fc.jpg)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/ef98acc57c54ae17674a6ef62130762b51f638ec
