### ISSUE TITLE
Add BSides 2018 Announcement

### ISSUE THREAD

**Issue by hiddenillusion** [bsidesnyc/bsidesnyc.github.io#24]
Resides in GDrive - should have a page for updates, or add to press?

**Comment by brad-anton** [comment]
Press release attached. Would be good to have the text and the pdf somewhere on the site
[BSidesNYC 2018 - Press Release.pdf](https://github.com/bsidesnyc/bsidesnyc.github.io/files/1603407/BSidesNYC.2018.-.Press.Release.pdf)

**Comment by brad-anton** [comment]
This press release is better, includes sponsors and partners! 
[Press Release.pdf](https://github.com/bsidesnyc/bsidesnyc.github.io/files/1603444/Press.Release.pdf)

**Comment by hiddenillusion** [comment]
Completed with https://github.com/bsidesnyc/bsidesnyc.github.io/commit/9ba75441063c8d3bffae6a1d93aec12f90deb5e4
