### ISSUE TITLE
Add HackNYC as partner

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#26]
Site is : www.hacknyc.com 
![hacknyc](https://user-images.githubusercontent.com/1035793/34262794-5a9ff1fe-e63b-11e7-9987-21f22330aaf0.png)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/7b79a3c4f5cafafaf725d75bfa8142afa3e081bb
