### ISSUE TITLE
Mikala to Entrepreneur Track 

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#27]
http://www.uplevelsecurity.com/

>Mikala Vidal is the vice president of marketing at Uplevel Security, an adaptive system of record and intelligence for modern security operations. In previous roles she’s helped cybersecurity companies like Cato Networks, Intralinks (acquired by Synchronoss), Exabeam, WatchDox (acquired by BlackBerry), NSFOCUS and Waterfall Security stand out in crowded markets, generate awareness, and gain market traction through targeted and effective storytelling. She is a data-driven marketer who believes that transparency and authenticity are instrumental in making a company and its marketing successful. 

![mikala](https://user-images.githubusercontent.com/1035793/34276562-fdd56fc8-e66f-11e7-80af-172871a1b6f2.jpg)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/ce184eb509e897231ef6bbcf9b0d102cfa84ee06
