### ISSUE TITLE
Add Red Canary as a Gold Sponsor

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#36]
We have a `.eps` on the drive too 
![redcanary logo](https://user-images.githubusercontent.com/1035793/34565209-e0b5251a-f127-11e7-8029-89b8a07b17b1.png)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/fafe74cd5f130d69709a0596af82479a0bff273f
