### ISSUE TITLE
Please Add Cortext Insight as a wonderful silver sponsor! 

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#38]
cortexinsight.com

![screen shot 2018-01-11 at 14 23 37](https://user-images.githubusercontent.com/1035793/34842948-0f90a8ba-f6db-11e7-82d6-c92719a7ec55.png)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/0d84422ceb902458f3e09814f896b70a4d8427fe
