### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#39]
something similar to this, but for HOPE
This was mostly borrowed from the Ada Initiative – Thanks for a great policy, we’re happy to apply it to our conference.

then:

s/HOPE/BSidesNYC

HOPE is dedicated to a harassment-free conference experience for everyone. The HOPE series of events are open, inclusive forums for sharing of ideas. HOPE participants include speakers, vendors, makers, tinkerers, families, students, and everyone else wanting to experience HOPE events and be part of the HOPE community.

It is important for participants to step beyond prejudices, societal norms, and other perspectives that lead to disrespect for people and groups. Everyone is welcome at HOPE events, regardless of race, class, gender identity or expression, age, ethnicity, religion, political beliefs, disability, sexual orientation, personal appearance, or education level, text editor choice, and other aspects of who we are.

In short: HOPE is a space for tolerance and respect.

HOPE strongly values free speech. We also value our attendees, and do not want any to feel marginalized or intimidated. We encourage talks that address hard topics. We also encourage everyone to think about how offhand comments they make about others may contribute to making some feel unwelcome in this community.

Vendors are encouraged to promote their products or ideas based on their own merits, not on the appearance of their staff. The HOPE conference staff members are available to provide guidance, and to mediate disputes, should they arise.

HOPE seeks to ensure no attendee is harassed. This includes, but is not limited to: deliberate intimidation, stalking, following, harassing photography or recording, disruption of talks or other events, inappropriate physical contact, or unwelcome sexual attention.

The conference staff reserves the right to eject anyone from the conference at any time. If you are being harassed, notice that someone else is being harassed, or have related concerns, we encourage you to contact a member of conference staff immediately.

(If you would like to use this code of conduct for your event or organization, feel free to credit or thank HOPE in whatever manner you wish.)

**Comment by hiddenillusion** [comment]
Since our existing anti-harassement policy is very similar, just changing the title to both.

fixed in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/82cde54da806d456687e16c652d89a0a9a790047
