### ISSUE TITLE
Galina's Bio and Twitter

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#40]
@GalinaAntova 

Galina Antova is cybersecurity executive and entrepreneur focused on OT/ICS cybersecurity. Galina co-founded Claroty to help advance the state of cybersecurity for critical infrastructure. Prior to that, she was the Global Head of Industrial Security Services at Siemens, overseeing development of its services that protect industrial customers against cyber-attacks. She was also responsible for leading its Cyber Security Practice and Cyber Security Operations Center, which provided managed security services for industrial control systems operators. Previously, Ms. Antova was with IBM Canada, with roles in the Provisioning and Cloud Solutions business. She holds a BS in Computer Science from York University in Toronto, and an MBA from the International Institute of Management and Development (IMD) in Lausanne, Switzerland.

**Comment by hiddenillusion** [comment]
Already added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/861a17b7c5aef5932ae2d6b60e7df566d2247cc6
