### ISSUE TITLE
Add Omri to Entrepreneur Track

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#41]
Omri Moyal // Co-Founder, VP Research

Omri is a curiosity-driven researcher and malware expert. Prior to Minerva Labs, Omri served as CTO of ClearSky Cybersecurity, where he led the development and implementation of a wide spread cyber intelligence monitoring network and was head of the Incident Response Team. In his previous roles Omri gained global experience and extensive expertise in reverse engineering, malware research and testing advanced malware solutions in both laboratory and enterprise production environments. Omri served in the Israel Defense Forces (IDF) Intelligence Unit and studied for a BSc in Computer and Information Sciences.

![image 8](https://user-images.githubusercontent.com/1035793/34878319-c9d880d4-f777-11e7-8d54-81d4457012a1.png)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/9fb0d44acf193792d60916b5b13e46824563de18

**Comment by brad-anton** [comment]
Sorry, small name correction: Omri Segev Moyal

**Comment by hiddenillusion** [comment]
Ok. Updated in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/2245a850a33a29c5505c7dc17e40cfc490c38a4f
