### ISSUE TITLE
Add Adrian to the Entrepreneur Track

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#42]
@cortexinsight @alien8 

Adrian is the Co-Founder and CEO of Cortex Insight.

Adrian has many years experience working within the security functions of industries and understands the business side of security.

Building and running companies & events in a number of vertical sectors has given him the skills and experience to lead the Cortex Insight team.

Adrian also founded alien8 Security, the European distributor for Immunity Inc. He is the Co-founder and Event Director of ‘44CON’ and Founder of Infosec in the City taking place in Singapore in May 2018.

Adrian has a MSc in Information Security from Royal Holloway and a BSc in Computer Science.

![dsc_4596 - copy 1](https://user-images.githubusercontent.com/1035793/34900141-7c641724-f7cb-11e7-8a66-64e5d7d58fd1.JPG)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/d36d5f84fa314a9dbc78a165370c94cdcabe06a6
