### ISSUE TITLE
Add Regina to the Entrepreneur Track

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#45]
REGINE GILBERT
Regine Gilbert is a user experience designer, educator, and international public speaker in NYC with over 10 years of experience working in the technology arena. Currently, she is a Sr. UX Design Consultant. Regine has a strong belief in making the world a more accessible place—one that starts and ends with the user.  She started her career in design as a fashion designer, then quickly evolved into working in a corporate information technology setting before returning to the world of design. She is passionate about accessibility, design and technology. 

Social Media: 

Twitter: @reg_inee
Linkedin: https://www.linkedin.com/in/reginegilbert

![head shot 3](https://user-images.githubusercontent.com/1035793/34918827-a71009e4-f927-11e7-8c73-5017ac54700b.png)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/63494db0ffd0c33def547d381eb85be970b9d075
