### ISSUE TITLE
Add Low Voltage Labs as a Partner! 

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#46]
http://lowvoltagelabs.com/

![lvl-logo](https://user-images.githubusercontent.com/1035793/34918844-cf8decd8-f927-11e7-84a2-a527c5480fe2.png)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/d1d7a7c558fb6187b513b41fd6937ee72517fae9
