### ISSUE TITLE
add ensilo as a silver sponsor! 

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#47]
https://www.ensilo.com/

[Horizontal Logo no tagline CMYK.PDF](https://github.com/bsidesnyc/bsidesnyc.github.io/files/1632101/Horizontal.Logo.no.tagline.CMYK.PDF)

**Comment by hiddenillusion** [comment]
need a different logo

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/37c919f782b663b08b704f55152e04677c73200e
