### ISSUE TITLE
add dispel as a silver sponsor! 

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#48]
dispel.io

![dispel_color_logo](https://user-images.githubusercontent.com/1035793/34951604-d7fa2ffe-f9e4-11e7-9b6a-57ced052a544.png)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/9696a57a7c73c92a6c81b54777f7f59dd2be992c
