### ISSUE TITLE
add EWF as partner

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#49]
http://www.ewf-usa.com/

![ewf_full_newlogo](https://user-images.githubusercontent.com/1035793/34952870-2059e420-f9e9-11e7-8b90-75d7156e9c01.jpg)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/7d86da2fe5e33aa3baea847fcc77990726bf8931
