### ISSUE TITLE
Add Splunk as a Silver Sponsor

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#50]
![logo_splunk_2color_k](https://user-images.githubusercontent.com/1035793/34996662-492fd7be-faa8-11e7-8a34-696d704fce0b.png)

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/b7559e02adbb35f80446fa50d8ce4d6dadf92d4f
