### ISSUE TITLE
Add details for Joe Bernik

### ISSUE THREAD

**Issue by hiddenillusion** [bsidesnyc/bsidesnyc.github.io#52]
- [x] add to Entrepreneur track
- [x] fill in details to `_data/people.yml`

**Comment by hiddenillusion** [comment]
need deets from @brad-anton for this profile creation

**Comment by brad-anton** [comment]
Joe Bernik has over two decades of experience creating and implementing cyber security management
programs at global financial institutions. While serving as CISO and head of information risk and security
at ABN AMRO Bank, Fifth Third Bank and BNY Mellon, Mr., Bernik lead global teams dedicated to
protecting customer data, complying with data-related laws and regulations, and managing incident
response programs. Mr. Bernik started his career with the US Defense Department of Defense (DOD)
securing military systems.
Joe has is an avid speaker and writer and has held posts on several industry groups including the
Federal Reserve Council on Fraud the Financial Services Information Sharing and Analysis Center
(FS-ISAC) and the Open Web Application Security Project (OWASP). Mr. Bernik holds a bachelors in
information systems from the University of Mary Washington and has completed graduate studies in
business administration at The City University of New York.

**Comment by brad-anton** [comment]
![joe-bernik_350px](https://user-images.githubusercontent.com/1035793/35018910-e81ad902-faf1-11e7-9217-e427470a605d.png)

**Comment by hiddenillusion** [comment]
finished adding in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/cd7a5e42282fd864a6d64e08673c5173baaf57c7
