### ISSUE TITLE
Add Ryan Young to the Entrepreneur Track!

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#55]
![screen shot 2018-01-18 at 09 20 38](https://user-images.githubusercontent.com/1035793/35102402-e39f6ba0-fc30-11e7-9c47-732c6810da76.png)

[MarketingAITG_Bio_Ryan Young-2018.pdf](https://github.com/bsidesnyc/bsidesnyc.github.io/files/1643101/MarketingAITG_Bio_Ryan.Young-2018.pdf)

**Comment by hiddenillusion** [comment]
Added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/18cd0fab617e7d36326fa21d5ca61b44900b4af7 & https://github.com/bsidesnyc/bsidesnyc.github.io/commit/10dd9e81c8488352cf821cb45bc9b434ef751bc9
