### ISSUE TITLE
Final Entrepreneur Track Schedule!!1

### ISSUE THREAD

**Issue by brad-anton** [bsidesnyc/bsidesnyc.github.io#56]
10:05-10:30 | Kelly Shortridge | Return Oriented: A 2017 Market Round Up
-- | -- | --
10:30-10:50 | Loren Mahler | The Things No One Tells You About Launching a Startup
11:00-11:25 | Galina Antova | Creating a New Security Product Category
11:25-11:50 | Paul Vixie | Bootstrapping
Lunch |   |  
13:00-13:25 | Roselle Safran | Venture Capital in Security
13:25-13:50 | Nicole Enslein | Marketing and Advertising for Security Startups
14:00-14:25 | Startup Panel | Steve Antoniewicz (Moderator), Mikala Vidal, Lenny Zeltser, Omri Segev Moyal, Regine Gilbert, Joe Bernik
14:25-14:50 | Startup Panel |  
15:00-15:25 | Kevin Chung | Growing & Monetizing Your Open Source Side Project
15:25-15:50 | Adrian Mahieu | Sales: How long until you really need it?
Coffee |   |  
16:00-16:25 | Jessica Santana | How Security Startups Can Help Build The Next Generation of Cyber Security Leaders
16:25-16:50 | Lenny Zeltser | Product Management for Security Products
17:00-17:25 | Ryan Young | (From) Concept to Profit
17:25-17:50 | Irena Damsky and Omri Segev Moyal | Startup Security Research

**Comment by hiddenillusion** [comment]
added in https://github.com/bsidesnyc/bsidesnyc.github.io/commit/10dd9e81c8488352cf821cb45bc9b434ef751bc9
